/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // Paleta Dark/Minimalista: apenas tons de cinza, chumbo e preto.
        error: '#e5e5e5',
        'on-error': '#0a0a0a',
        'error-container': '#4a4a4a',
        'on-error-container': '#f2f2f2',
        background: '#0d0d0d',
        surface: '#0d0d0d',
        'surface-bright': '#262626',
        'surface-container-lowest': '#161616',
        'surface-container-low': '#1e1e1e',
        'surface-container': '#292929',
        'surface-container-high': '#333333',
        'surface-variant': '#3d3d3d',
        'on-surface': '#ececec',
        'on-surface-variant': '#b3b3b3',
        outline: '#8a8a8a',
        'outline-variant': '#4d4d4d',
        primary: '#f5f5f5',
        'on-primary': '#0a0a0a',
        'primary-container': '#c9c9c9',
        secondary: '#a6a6a6',
        'secondary-container': '#5c5c5c',
        'on-secondary-container': '#e0e0e0',
      },
      borderRadius: { DEFAULT: '0.125rem', lg: '0.25rem', xl: '0.5rem', full: '0.75rem' },
      spacing: {
        'space-xs': '0.25rem',
        'space-xl': '2rem',
        gutter: '1rem',
        'space-sm': '0.5rem',
        'space-md': '0.75rem',
        'space-lg': '1.25rem',
        margin: '1.5rem',
      },
      fontFamily: {
        'body-md': ['Inter', 'sans-serif'],
        'headline-lg': ['Inter', 'sans-serif'],
        'headline-sm': ['Inter', 'sans-serif'],
        'display-lg': ['Inter', 'sans-serif'],
        'data-mono': ['JetBrains Mono', 'monospace'],
        'label-md': ['Inter', 'sans-serif'],
        'body-sm': ['Inter', 'sans-serif'],
        'label-sm': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'body-md': ['13px', { lineHeight: '18px', fontWeight: '400' }],
        'headline-lg': ['24px', { lineHeight: '32px', letterSpacing: '-0.015em', fontWeight: '600' }],
        'headline-sm': ['18px', { lineHeight: '26px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'display-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'data-mono': ['12px', { lineHeight: '16px', fontWeight: '500' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.02em', fontWeight: '600' }],
        'body-sm': ['12px', { lineHeight: '16px', fontWeight: '400' }],
        'label-sm': ['11px', { lineHeight: '14px', letterSpacing: '0.04em', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
}
